---

allow_duplicates: yes

galaxy_info:
  author: Robin Clarke, Jakob Reiter, Dale McDiarmid
  description: Elasticsearch for Linux
  company: "Elastic.co"
  license: "license (Apache)"
  min_ansible_version: 2.3.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - system

dependencies: []
