---
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages }}"

- name: install python packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_packages }}"

- name: create required directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ vulnwhisperer.prefix }}"
    - "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.location }}"

- name: deploy application
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.location }}"
    force: yes
    repo: "{{ vulnwhisperer.repository }}"
  register: repository

- name: create virtualenv
  pip:
    virtualenv: "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.venv_location }}"
    requirements: "{{ vulnwhisperer.prefix  }}/{{ vulnwhisperer.location  }}/requirements.txt"
    virtualenv_python: /usr/bin/python2.7

# no longer necessary after qualysapi fix
#- name: add qualys package to virtualenv
#  command: "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.venv_location }}/bin/python setup.py install"
#  args:
#    chdir: "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.location }}/deps/qualysapi"

- name: install vulnwhisperer in virtualenv
  command: "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.venv_location }}/bin/python setup.py install"
  args:
    chdir: "{{ vulnwhisperer.prefix }}/{{ vulnwhisperer.location }}"
 
